### ISSUE TITLE
Getting Started errors

### ISSUE THREAD

**Issue by swcurran** [hyperledger-labs/did-webs-resolver#40]
Tried the Getting Started guide and ran into trouble:

1. On the `kli init` step, the action worked, but the expected output about the OOBIs was not printed.
2. On the `kli incept` command, there was an error printed, and I noticed that the `my-scripts/incept.json` file was not in the image.

Any ideas on the issues?

**Comment by 2byrds** [comment]
Thank you for reporting!
I'm happy to do a session together with you since you are one of the first to test (if you like).
Som initial notes: 

First, it is good to make sure you aren't using any old image builds. So please double check that you built with --no-cache flag.

 Looking at the config-docker file for the init command, it specifies the witnesses in iurls:
https://github.com/hyperledger-labs/did-webs-resolver/blob/main/volume/dkr/examples/my-scripts/keri/cf/config-docker.json

And the docker compose up should have started the witnesshost service https://github.com/hyperledger-labs/did-webs-resolver/blob/main/docker-compose.yml#L14

Can you try to curl one of the witness OOBIs from your webs docker contianer to see if the oobi is addressable? Also send me the command/output that you see when running init.

I'll go back and try to test a cleaner env, perhaps i have some local files or something.

**Comment by 2byrds** [comment]
@swcurran thank you for the PR. I clean my env and ran with your changes and it looks good for me. Note: if you want to run the commands quickly you can execute the ./get_started_docker.sh from the volume/dkr/examples dir (during that script there will be an opportunity to start up your file server via the GETTING_STARTED instructions.... i need to add some prompt that says that)

**Comment by 2byrds** [comment]
fixed by https://github.com/hyperledger-labs/did-webs-resolver/pull/41
